apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellorepli
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hellorepli
  template:
    metadata:
      labels:
        app: hellorepli
    spec:
      containers:
      - name: hellorepli
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: hellorepli
  annotations:
    konghq.com/plugins: five-per-min
spec:
  type: ClusterIP
  selector:
    app: hellorepli
  ports:
  - port: 80
    targetPort: 8080